"""create DBmeta

Revision ID: eb397942a98a
Revises: 8d7ce3fa2a22
Create Date: 2025-08-17 18:03:47.718972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb397942a98a'
down_revision: Union[str, Sequence[str], None] = '8d7ce3fa2a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_meta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('bookings_property_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_property_id_fkey'), 'bookings', 'properties', ['property_id'], ['id'])
    op.drop_table('db_meta', schema='public')
    # ### end Alembic commands ###
